Added git detection handler
itk-dev/devops_itksites pull request #13
Opened 2022-06-24 11:04 UTC by afrje

#### Link to ticket

No ticket

#### Description

Added git detection handler

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Checklist

- [ ] My code is covered by test cases.
- [ ] My code passes our test (all our tests).
- [ ] My code passes our static analysis suite.
- [ ] My code passes our continuous integration process.

If your code does not pass all the requirements on the checklist you have to add a comment explaining why this change 
should be exempt from the list.

#### Additional comments or questions

If you have any further comments or questions for the reviewer please add them here.

2022-06-29 09:38 UTC, turegjorup requested changes

2022-06-29 09:38 UTC, turegjorup commented on src/Controller/Admin/DashboardController.php
> +        yield MenuItem::linkToCrud('Git', 'fas fa-folder', Git::class);
Consider using one of the icons here: https://fontawesome.com/icons/github-square?s=brands

E.g. dp `'fas fa-github'`

2022-06-29 09:38 UTC, turegjorup commented on src/Command/ReplayDetectionResultsCommand.php
> +                'Limit replay to this type. Options are ['.join(', ', DetectionType::CHOICES).']');
Suggestion: It's also possible to use https://symfony.com/doc/current/components/console/helpers/questionhelper.html to give the user a "dropdown"

2022-06-29 09:38 UTC, turegjorup commented on src/Controller/Admin/GitCrudController.php
> +        return Git::class;
We should choose if this is `Git` or `Github`. I lean towrads `Github` but am open to arguments against

2022-06-29 09:38 UTC, turegjorup commented on src/Controller/Admin/GitCrudController.php
> +        yield TextField::new('changes')->setColumns(6); // ->hideOnIndex();
As you suggested. This should propably by hidden on the index page. 

You can do a virtual field to just highlight if there is changes.

2022-06-29 09:38 UTC, turegjorup commented on src/Command/ReplayDetectionResultsCommand.php
> +        $detectionResults = $this->entityManager->createQueryBuilder()
Suggest `$queryBuilder`

2022-06-29 09:38 UTC, turegjorup commented on src/Controller/Admin/GitCrudController.php
> +    public function configureFields(string $pageName): iterable
Remove please

2022-09-05 11:51 UTC, turegjorup requested changes

2022-09-05 11:51 UTC, turegjorup commented on composer.json
> +        "symfony/var-dumper": "6.1.*",
Please use the `^6.1` format as above. This allows semver safe updates

2022-09-05 11:51 UTC, turegjorup commented on composer.json
> -            "vendor/bin/php-cs-fixer fix"
Why is this removed?

2022-09-05 11:51 UTC, turegjorup commented on src/Handler/GitHandler.php
> +                        var_dump($e);
This is debug code, should be removed or converted to proper exception handling.

2022-09-05 11:51 UTC, turegjorup commented on src/Handler/GitHandler.php
> +                        var_dump($e);
This is debug code, should be removed or converted to proper exception handling.

2022-09-05 11:51 UTC, turegjorup commented on src/Entity/ModuleVersion.php
> +    public function display(int $style): string
Using integers doesn't relay what the parameter does. Using a value like `detail` does that better. Also please document the parameter with a proper phpDoc block https://docs.phpdoc.org/3.0/guide/getting-started/what-is-a-docblock.html

2022-09-05 11:51 UTC, turegjorup commented on src/Twig/AppExtension.php
> +    public function has_display(AbstractBaseEntity $entity): bool
Should be `hasDisplay` to follow standard naming

2022-09-05 11:51 UTC, turegjorup commented on src/Twig/AppExtension.php
> +    public function entity_display(AbstractBaseEntity $entity, string $action): string
Should be `entityDisplay` to follow standard naming

2022-09-09 08:44 UTC, afrje commented on composer.json
> -            "vendor/bin/php-cs-fixer fix"
Was your suggesting because "coding-standards-apply" execute the same command.

2022-09-26 14:06 UTC, turegjorup approved these changes

2022-09-26 14:07 UTC, merged